 17/172 [=>............................] - ETA: 2s - loss: 4.1292Ignoring exception in on_ready
 1/65 [..............................] - ETA: 3:45 - loss: 25.3530Ignoring exception in on_ready
tim_1       | Traceback (most recent call last):
tim_1       |   File "/opt/conda/lib/python3.9/site-packages/discord/client.py", line 343, in _run_event
tim_1       |     await coro(*args, **kwargs)
tim_1       |   File "/app/main.py", line 26, in on_ready
tim_1       |     await handle_replies()
tim_1       |   File "/app/bot_src/main.py", line 35, in handle_replies
tim_1       |     await handle_recent_replies()
tim_1       |   File "/app/bot_src/main.py", line 30, in handle_recent_replies
tim_1       |     await channel.send(reply["content"])
tim_1       | AttributeError: 'NoneType' object has no attribute 'send'
hivemind_1  | Traceback (most recent call last):
hivemind_1  |   File "/opt/conda/lib/python3.9/site-packages/discord/client.py", line 343, in _run_event
hivemind_1  |     await coro(*args, **kwargs)
hivemind_1  |   File "/app/main.py", line 26, in on_ready
hivemind_1  |     await handle_replies()
hivemind_1  |   File "/app/bot_src/main.py", line 35, in handle_replies
hivemind_1  |     await handle_recent_replies()
hivemind_1  |   File "/app/bot_src/main.py", line 30, in handle_recent_replies
hivemind_1  |     await channel.send(reply["content"])
hivemind_1  | AttributeError: 'NoneType' object has no attribute 'send'
tim_1       | hanldling reply
tim_1       | {'author': 449279570445729793, 'channel': 483860795575238657, 'content': 'The policewomen are cooking me! :ok_hand:'}
tim_1       | 483860795575238657
tim_1       | None
tim_1       | this bot tried to send to a channel it can't see
tim_1       | 343299242963763200
tim_1       | None
hivemind_1  | hanldling reply
hivemind_1  | {'author': '173819538008309760', 'channel': '343179912196128792', 'content': 'I think that is server', 'server': '381467097030459393'}
hivemind_1  | 343179912196128792
hivemind_1  | None
hivemind_1  | this bot tried to send to a channel it can't see
hivemind_1  | 343299242963763200
hivemind_1  | None
1/1 [==============================] - 0s 20ms/step
1/1 [==============================] - 0s 21ms/step
1/1 [==============================] - 0s 52ms/step:11 - loss: 30.8435
1/1 [==============================] - 0s 17ms/step- loss: 4.0324
1/1 [==============================] - 0s 18ms/step
1/1 [==============================] - 0s 56ms/step
duck_1      | Ignoring exception in on_ready
duck_1      | Traceback (most recent call last):
duck_1      |   File "/opt/conda/lib/python3.9/site-packages/discord/client.py", line 343, in _run_event
duck_1      |     await coro(*args, **kwargs)
duck_1      |   File "/app/main.py", line 26, in on_ready
duck_1      |     await handle_replies()
duck_1      |   File "/app/bot_src/main.py", line 35, in handle_replies
duck_1      |     await handle_recent_replies()
duck_1      |   File "/app/bot_src/main.py", line 30, in handle_recent_replies
duck_1      |     await channel.send(reply["content"])
duck_1      | AttributeError: 'NoneType' object has no attribute 'send'
1/1 [==============================] - 0s 23ms/step- loss: 3.8917
1/1 [==============================] - 0s 23ms/step
1/1 [==============================] - 0s 134ms/steploss: 25.0295 
1/1 [==============================] - 0s 136ms/step
duck_1      | hanldling reply
duck_1      | {'author': 449279570445729793, 'channel': 483860795575238657, 'content': 'The policewomen are cooking me! :ok_hand:'}
duck_1      | 483860795575238657
duck_1      | None
duck_1      | this bot tried to send to a channel it can't see
duck_1      | 343299242963763200
duck_1      | None
1/1 [==============================] - 0s 18ms/step- loss: 3.7389
1/1 [=========================
