{"author":"439205512425504771","bot":true,"channel":"343299242963763200","content":"```py\nThe directory '/var/www/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.\nThe directory '/var/www/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.\nException:\nTraceback (most recent call last):\n  File \"/usr/local/lib/python2.7/dist-packages/pip/basecommand.py\", line 215, in main\n    status = self.run(options, args)\n  File \"/usr/local/lib/python2.7/dist-packages/pip/commands/install.py\", line 289, in run\n    delete=build_delete) as build_dir:\n  File \"/usr/local/lib/python2.7/dist-packages/pip/utils/build.py\", line 22, in __init__\n    name = os.path.realpath(tempfile.mkdtemp(prefix=\"pip-build-\"))\n  File \"/usr/lib/python2.7/tempfile.py\", line 331, in mkdtemp\n    dir = gettempdir()\n  File \"/usr/lib/python2.7/tempfile.py\", line 275, in gettempdir\n    tempdir = _get_default_tempdir()\n  File \"/usr/lib/python2.7/tempfile.py\", line 217, in _get_default_tempdir\n    (\"No usable temporary directory found in %s\" % dirlist))\nIOError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/var/www/service/usercode']\n```","created":1528242509166,"id":"453706710163390465","server":"343179912196128792"}